### ISSUE TITLE
Which paper does the code correspond to?

### ISSUE THREAD

**Issue by hjing100** [yahshibu/nested-ner-2019-bert#5]
Which paper does the code correspond to? Thank you.

**Comment by yahshibu** [comment]
Thank you for having an interest in our work.

I added some tags, each of which corresponds to a version of our arXiv paper.

[Tag arxiv_v3](https://github.com/yahshibu/nested-ner-tacl2020-transformers/tree/arxiv_v3) corresponds to https://arxiv.org/abs/1909.02250v3.
[Tag arxiv_v2](https://github.com/yahshibu/nested-ner-tacl2020-transformers/tree/arxiv_v2) corresponds to https://arxiv.org/abs/1909.02250v2.
[Tag arxiv_v1](https://github.com/yahshibu/nested-ner-tacl2020-transformers/tree/arxiv_v1) corresponds to https://arxiv.org/abs/1909.02250v1.

v3 is the latest version and identical to [our TACL paper](https://www.mitpressjournals.org/doi/full/10.1162/tacl_a_00334).

**Comment by hjing100** [comment]
Thank you, I see.
