### ISSUE TITLE
reader.py/_pad_batches() use sent_len = len(first_subtokens_batch[i]) ?

### ISSUE THREAD

**Issue by hjing100** [yahshibu/nested-ner-2019-bert#6]
reader.py/_pad_batches() use sent_len = len(first_subtokens_batch[i]) ?
I don't understand why is first_subtokens_batch get sent_len, not input_mask_batch?

Another question，reader.py/to_batch()
(1)label_list = [(u[0], u[1], self.label_alphabet.get_index(u[2])) for u in sentInst.entities] # entity  start_position、end_posiotn、token_label_index
(2)st = bert_tokenizer.tokenize(t)
Can (1) and (2) correspond?

**Comment by yahshibu** [comment]
Thank you for having an interest in our work.


> reader.py/_pad_batches() use sent_len = len(first_subtokens_batch[i]) ?

reader.py handles two types of sequences: (a) sequences of words, and (b) sequences of subtokens (generated by WordPiece tokenizer). For example, the BERT tokenizer split a word sequence "andrew luster" into a subtoken sequence "andrew lust ##er".
```
                subtokens_num = len(input_ids_batch[i])
                sent_len = len(first_subtokens_batch[i])
```
`subtokens_sum` is the length of a subtoken sequence, and `sentlen` is the length of a word sequence. I regard a sequence of words as an original sequence, and I regard a sequence of subtokens as an intermediate state for using BERT. This is why I use the name "sent_len" for the length of a word sequence.


> reader.py/to_batch()
> (1)label_list = [(u[0], u[1], self.label_alphabet.get_index(u[2])) for u in sentInst.entities] # entity start_position、end_posiotn、token_label_index
> (2)st = bert_tokenizer.tokenize(t)
> Can (1) and (2) correspond?

No. (1) is represented with words, but (2) is a list of subtokens.

**Comment by hjing100** [comment]
I see. Thank you very much.
