### ISSUE TITLE
BUG: IndexError in sequence_labeling.py

### ISSUE THREAD

**Issue by XinyanLi2016** [yahshibu/nested-ner-2019-bert#8]
Hi, yahshibu!
Recently, I retrain your code with GENIA corpus without fine tuning.
But I met an error, which is "IndexError: tuple index out of range".
Traceback shows as this:
![image](https://user-images.githubusercontent.com/30367040/138702021-ceb85943-3ecc-41e1-b8a1-77f51ba50bd6.png)

I can't find why this error happened. Could you help me? Thanks a lot!

**Comment by yahshibu** [comment]
Thank you for having an interest in our work.

Could you try using PyTorch **v1.6.0** and Transformers **v2.1.1** instead of the latest versions of them? I believe that this will work.

I'm sorry I'm busy now and I can't immediately fix a bug under the latest versions.

**Comment by XinyanLi2016** [comment]
Thanks for your reply, I will try it!

**Comment by mahmoudSalim** [comment]
Hi @yahshibu 
I have a similar error and I'm using PyTorch **v1.6.0** and Transformers **v2.1.1**
When running `train.py`, it runs the first epoch just fine and save a checkpoint in dumps folder, but before executing the second epoch that error appears.
![Screenshot from 2021-10-28 17-38-34](https://user-images.githubusercontent.com/15940968/139291186-fc22d973-4ee1-4b6a-b6f1-01efb2f9a1b9.jpg)

**Comment by yahshibu** [comment]
@XinyanLi2016 @mahmoudSalim 
I updated this repository so that it works with the latest versions, PyTorch (v1.10.0) and Transformers (v4.12.0). I've confirmed that this works on my local computer.
Could you update your local code and try it? Sorry for bothering you.
